FROM ubuntu:14.04
LABEL name="Manisha"
LABEL email="manishakumari200307@gmail.com"
ENV NAME manisha
ENV PASSWORD password
RUN pwd>/tmp/1stpwd.txt
RUN cd /tmp
RUN pwd>/tmp/2ndpwd.txt
WORKDIR /tmp
RUN pwd>/tmp/3rdpwd.txt 
