FROM ubuntu:14.04
RUN apt-get update &&  apt-get install -y tree && apt-get install -y git
RUN touch /tmp/abc.txt
RUN touch /tmp/1.txt
RUN touch /tmp/2.txt
RUN touch /tmp/3.txt
RUN touch /tmp/4.txt
RUN touch /tmp/5.txt
RUN touch /tmp/6.txt
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
RUN echo "Hi My Name is Manisha"
