version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.4-alpine
    image: python-redis-2
    ports:
      - "5000:5000"
    
  redis:
    image: "redis:alpine"